### ISSUE TITLE
Null error for tooltips on Followers

### ISSUE THREAD

**Issue by Xruptor** [alarofrunetotem/OrderHallCommander#1]
https://github.com/alarofrunetotem/OrderHallCommander/blob/b8d6ab02b5eebe961a50a38d0aebcbbe786f63fd/OrderHallCommander.lua#L466

Sometimes link is returned null.  It causes a follower tooltip bug.  As a suggestion you may want to do a null check.

Under line 466 I suggest the following:
`if not link then return end`

It's simple and should prevent the error from popping up on the quick completion screen or when viewing missions.

**Comment by alar77** [comment]
Fixed
