### ISSUE TITLE
Not working on most classes

### ISSUE THREAD

**Issue by infinityinc** [alarofrunetotem/OrderHallCommander#15]
So far this only works on my Pally and Shaman - no %s or auto-fill parties for Mage, DH, Hunter.

Running pretty minimum addons - Elvui, Recount, Postal, DBM, Bagnon, Garrison/OrderHall/BfA commanders.

**Comment by alar77** [comment]
Just tested on a demon hunter so I dont think issue is in class. Maybe some weird mission OHC cant manage?
Do you have something like BugGrabber / Bugsack?
Your error listing could really help

**Comment by infinityinc** [comment]
30x OrderHallCommander\cache.lua:901: attempt to compare number with nil
[string "@OrderHallCommander\cache.lua"]:901: in function `GetFullPermutations'
[string "@OrderHallCommander\matchmaker.lua"]:691: in function `?'
[string "@OrderHallCommander\missionlist.lua"]:544: in function <OrderHallCommander\missionlist.lua:528>
[string "=(tail call)"]: ?
[string "@OrderHallCommander\missionlist.lua"]:573: in function `ReloadMissions'
[string "@OrderHallCommander\missionlist.lua"]:745: in function <OrderHallCommander\missionlist.lua:726>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2928: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2734: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2641: in function <FrameXML\UIParent.lua:2637>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3492: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:1976: in function <FrameXML\UIParent.lua:1287>

Locals:
self = <table> {
 MAXLEVEL = <function> defined @OrderHallCommander\OrderHallCommander.lua:137
 modules = <table> {
 }
 CancelTimer = <function> defined @ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 IsBlacklisted = <function> defined @OrderHallCommander\core.lua:165
 GetAverageLevels = <function> defined @OrderHallCommander\cache.lua:944
 allEquipments = <table> {
 }
 RebuildMissionCache = <function> defined @OrderHallCommander\cache.lua:931
 GetDataModule = <function> defined @OrderHallCommander\data.lua:14
 ActivateButton = <function> defined @OrderHallCommander\core.lua:199
 GetDifficultyColors = <function> defined @OrderHallCommander\core.lua:226
 GetMissionlistModule = <function> defined @OrderHallCommander\missionlist.lua:16
 SetDefaultModulePrototype = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 MAXQUALITY = <function> defined @OrderHallCommander\OrderHallCommander.lua:140
 GetResources = <function> defined @OrderHallCommander\cache.lua:744
 GetCacheModule = <function> defined @OrderHallCommander\cache.lua:16
 IsEnabled = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 GetCompletedMissionData = <function> defined @OrderHallCommander\autocomplete.lua:570
 MarkAsSeen = <function> defined @OrderHallCommander\core.lua:289
 ReloadMissions = <function> defined @OrderHallCommander\missionlist.lua:566
 RegisterMessage = <function> defined @ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @ElvUI\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Pulse = <function> defined @OrderHallCommander\missionlist.lua:642
 hooks = <table> {
 }
 db = <table> {
 }
 PauseApply = <function> defined @OrderHallCommander\missionlist.lua:495
 Apply = <function> defined @OrderHallCommander\missionlist.lua:498
 SetEnabledState = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:274
 EmptyPermutations = <function> defined @OrderHallCommander\cache.lua:849
 PushRefresher = <function> defined @OrderHallCommander\missionlist.lua:557
 Reserve = <function> defined @OrderHallCommander\OrderHallCommander.lua:213
 Reward2Class = <function> defined @OrderHallCommander\cache.lua:432
 ColorFromBias = <function> defined @OrderHallCommander\OrderHallCommander.lua:149
 NeedsTutorial = <function> defined @OrderHallCommander\tutorials.lua:413
 ShowPermutations = <function> defined @OrderHallCommander\missionpage.lua:290
 OnInitialized = <function> defined @OrderHallCommander\core.lua:142
 GetMissionpageModule = <function> defined @OrderHallCommander\missionpage.lua:16
 NewModule = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 GetMembersFrame = <function> defined @OrderHallCommander\missionlist.lua:808
 SortTroop = <function> defined @OrderHallCommander\cache.lua:814
 CleanPermutations = <function> defined @OrderHallCommander\missionlist.lua:393
 revision = "cc8ae7d"
 Unban = <function> defined @OrderHallCommander\OrderHallCommander.lua:228
 GetSelectedParty = <function> defined @OrderHallCommander\matchmaker.lua:653
 GetName = <function> defined @ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 DumpPermutations = <function> defined @OrderHallCommander\cache.lua:923
 name = "OrderHallCommander"
 Refi

Dump I just did on my Mage.

**Comment by infinityinc** [comment]
Just tested again with Mage and DH this morning - only addon on is OrderCommander - again no %s or autofill and a shitton of lua errors upon opening table. Should also be noted this a fresh install of WoW day after 9.2 launch.

p.s. the vitality heal a troop thingies haven't worked on any toon in a very long time.

**Comment by alar77** [comment]
Fix attempt in 1.9.1
