### ISSUE TITLE
Lua Error in 9.1.5

### ISSUE THREAD

**Issue by Vandakter** [alarofrunetotem/OrderHallCommander#16]
Hello,

As of 9.1.5, I have been getting this error:

Message: Interface\AddOns\OrderHallCommander\cache.lua:541: attempt to index field 'Background' (a nil value)
Time: Fri Nov 12 09:57:19 2021
Count: 2
Stack: Interface\AddOns\OrderHallCommander\cache.lua:541: attempt to index field 'Background' (a nil value)
[string "@Interface\AddOns\OrderHallCommander\cache.lua"]:541: in function `GetTroopsFrame'
[string "@Interface\AddOns\OrderHallCommander\cache.lua"]:665: in function `?'
[string "@Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Scrap\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...face\AddOns\Scrap\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Skullcan** [comment]
Replace the line 541 of the cache.lua file
old:
frame.Background:Hide()
new:
-- frame.Background:Hide()

You can also delete the line 541.

**Comment by crypticasden** [comment]
Since this project looks to be abandoned this workaround works in 9.2

**Comment by vince2paname** [comment]
Seems definitly broken in 10.0.0 :(
