### ISSUE TITLE
Bug Orderhallcommander

### ISSUE THREAD

**Issue by GeoRam2016** [alarofrunetotem/OrderHallCommander#18]
Hi
I play the Legion and there is a OrderHall Bug.
Is there a Chance to fix it?

21x OrderHallCommander\cache.lua:541: attempt to index field 'Background' (a nil value)
[string "@OrderHallCommander\cache.lua"]:541: in function `GetTroopsFrame'
[string "@OrderHallCommander\cache.lua"]:665: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by crypticasden** [comment]
Replace line 541 of the cache.lua file
old:
frame.Background:Hide()
new:
-- frame.Background:Hide()

You can also delete the line 541.

Edit: there's a PR #17 with a fix but the owner has to aprove/merge it and create a new release. 

Also works in 9.2
