### ISSUE TITLE
v1.9.1 several LUA errors with DF prepatch

### ISSUE THREAD

**Issue by LiquidAtoR** [alarofrunetotem/OrderHallCommander#20]
`Message: Interface/AddOns/OrderHallCommander/autopilot.lua:106: attempt to index field 'listScroll' (a nil value)
Time: Sat Nov 12 01:42:23 2022
Count: 1
Stack: Interface/AddOns/OrderHallCommander/autopilot.lua:106: attempt to index field 'listScroll' (a nil value)
[string "@Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua"]:769: in function <...Ons/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:725>
[string "=[C]"]: ?
[string "@Interface/AddOns/OrderHallCommander/autopilot.lua"]:106: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:530: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:727: in function `Garrison_LoadUI'
[string "@Interface/AddOns/WarPlan/MissionTable.lua"]:476: in function <Interface/AddOns/WarPlan/MissionTable.lua:471>
[string "=[C]"]: ?
[string "@Interface/AddOns/WarPlan/Libs/Evie.lua"]:37: in function <Interface/AddOns/WarPlan/Libs/Evie.lua:32>

Locals: errMsg = "Interface/AddOns/OrderHallCommander/autopilot.lua:106: attempt to index field 'listScroll' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:525
 ErrorHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface/SharedXML/SharedBasicControls.lua:360
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:544
 num = 0
 SanitizeString = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:518
 AddonBlockedHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}
`

`Message: Interface/AddOns/OrderHallCommander/missionlist.lua:138: attempt to index field 'listScroll' (a nil value)
Time: Sat Nov 12 01:42:23 2022
Count: 1
Stack: Interface/AddOns/OrderHallCommander/missionlist.lua:138: attempt to index field 'listScroll' (a nil value)
[string "@Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua"]:769: in function <...Ons/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:725>
[string "=[C]"]: ?
[string "@Interface/AddOns/OrderHallCommander/missionlist.lua"]:138: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:530: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:727: in function `Garrison_LoadUI'
[string "@Interface/AddOns/WarPlan/MissionTable.lua"]:476: in function <Interface/AddOns/WarPlan/MissionTable.lua:471>
[string "=[C]"]: ?
[string "@Interface/AddOns/WarPlan/Libs/Evie.lua"]:37: in function <Interface/AddOns/WarPlan/Libs/Evie.lua:32>

Locals: errMsg = "Interface/AddOns/OrderHallCommander/missionlist.lua:138: attempt to index field 'listScroll' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:525
 ErrorHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface/SharedXML/SharedBasicControls.lua:360
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:544
 num = 0
 SanitizeString = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:518
 AddonBlockedHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}
`

`Message: Interface/AddOns/OrderHallCommander/tutorials.lua:106: attempt to index field 'listScroll' (a nil value)
Time: Sat Nov 12 01:42:23 2022
Count: 1
Stack: Interface/AddOns/OrderHallCommander/tutorials.lua:106: attempt to index field 'listScroll' (a nil value)
[string "@Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua"]:769: in function <...Ons/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:725>
[string "=[C]"]: ?
[string "@Interface/AddOns/OrderHallCommander/tutorials.lua"]:106: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:530: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:727: in function `Garrison_LoadUI'
[string "@Interface/AddOns/WarPlan/MissionTable.lua"]:476: in function <Interface/AddOns/WarPlan/MissionTable.lua:471>
[string "=[C]"]: ?
[string "@Interface/AddOns/WarPlan/Libs/Evie.lua"]:37: in function <Interface/AddOns/WarPlan/Libs/Evie.lua:32>

Locals: errMsg = "Interface/AddOns/OrderHallCommander/tutorials.lua:106: attempt to index field 'listScroll' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:525
 ErrorHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface/SharedXML/SharedBasicControls.lua:360
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:544
 num = 0
 SanitizeString = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:518
 AddonBlockedHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}
`

`Message: Interface/AddOns/OrderHallCommander/OrderHallCommander.xml:82 Unrecognized XML attribute: strata
Time: Sat Nov 12 01:42:23 2022
Count: 2`

`Message: Interface/AddOns/OrderHallCommander/OrderHallCommander.xml:324 Unrecognized XML attribute: mouseEnable
Time: Sat Nov 12 01:42:23 2022
Count: 2`

`Message: Interface/AddOns/OrderHallCommander/autopilot.lua:1 (null)
Time: Sat Nov 12 01:42:23 2022
Count: 2`

`Message: Interface/AddOns/OrderHallCommander/missionlist.lua:1 (null)
Time: Sat Nov 12 01:42:23 2022
Count: 2`

`Message: Interface/AddOns/OrderHallCommander/tutorials.lua:1 (null)
Time: Sat Nov 12 01:42:23 2022
Count: 2`

**Comment by Caerdon** [comment]
This is fixed in my pull request: https://github.com/alarofrunetotem/OrderHallCommander/pull/21

**Comment by LiquidAtoR** [comment]
Will give it a rundown then

**Comment by Naxterra** [comment]
When will it get active and can be downloaded?
